version: '3'

services:
  api-gateway:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-api-gateway:prod
    restart: on-failure
    ports:
      - "3000:3000"
    build:
      context: ./api-gateway
      target: production
    environment:
      NODE_ENV: production
    env_file: ./api-gateway/.env.example
    depends_on:
      - rabbitmq


  auth:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-auth:prod
    restart: on-failure
    build:
      context: ./auth
      target: production
    environment:
      NODE_ENV: production
    env_file: ./auth/.env.example


  mailer:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-mailer:prod
    restart: on-failure
    build:
      context: ./mailer
      target: production
    environment:
      NODE_ENV: production
    env_file: ./mailer/.env.example


  verification-token:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-verification-token:prod
    restart: on-failure
    build:
      context: ./verification-token
      target: production
    environment:
      NODE_ENV: production
    env_file: ./verification-token/.env.example


  feedback:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-feedback:prod
    restart: on-failure
    build:
      context: ./feedback
      target: production
    environment:
      NODE_ENV: production
    env_file: ./feedback/.env.example


  files:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-files:prod
    restart: on-failure
    build:
      context: ./files
      target: production
    environment:
      NODE_ENV: production
    env_file: ./files/.env


  class-and-category:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-class-and-category:prod
    restart: on-failure
    build:
      context: ./class-and-category
      target: production
    environment:
      NODE_ENV: production
    env_file: ./class-and-category/.env.example


  tutor-apply-for-class:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-tutor-apply-for-class:prod
    restart: on-failure
    build:
      context: ./tutor-apply-for-class
      target: production
    environment:
      NODE_ENV: production
    env_file: ./tutor-apply-for-class/.env.example


  student-favorite-tutor:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-student-favorite-tutor:prod
    restart: on-failure
    build:
      context: ./student-favorite-tutor
      target: production
    environment:
      NODE_ENV: production
    env_file: ./student-favorite-tutor/.env.example


  tutor-proficient-in-class-category:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-tutor-proficient-in-class-category:prod
    restart: on-failure
    build:
      context: ./tutor-proficient-in-class-category
      target: production
    environment:
      NODE_ENV: production
    env_file: ./tutor-proficient-in-class-category/.env.example


  tutor-query:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-tutor-query:prod
    restart: on-failure
    build:
      context: ./tutor-query
      target: production
    environment:
      NODE_ENV: production
    env_file: ./tutor-query/.env.example

  address:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-address:prod
    restart: on-failure
    build:
      context: ./address
      target: production
    environment:
      NODE_ENV: production
    env_file: ./address/.env.example

  class-session:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-class-session:prod
    restart: on-failure
    build:
      context: ./class-session
      target: production
    environment:
      NODE_ENV: production
    env_file: ./class-session/.env.example

  report:
    image: registry.digitalocean.com/tutorify-registry/tutorify-be-report:prod
    restart: on-failure
    build:
      context: ./report
      target: production
    environment:
      NODE_ENV: production
    env_file: ./report/.env.example

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
