services:
  api-gateway:
    image: tutorify-be-api-gateway:dev
    restart: no
    build:
      context: ./api-gateway
      target: development
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./api-gateway:/usr/src/app
      - ./shared:/usr/src/shared
    depends_on:
      - rabbitmq


  auth:
    image: tutorify-be-auth:dev
    restart: no
    build:
      context: ./auth
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./auth:/usr/src/app
      - ./shared:/usr/src/shared

  mailer:
    image: tutorify-be-mailer:dev
    restart: no
    build:
      context: ./mailer
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./mailer:/usr/src/app


  verification-token:
    image: tutorify-be-verification-token:dev
    restart: no
    build:
      context: ./verification-token
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./verification-token:/usr/src/app


  feedback:
    image: tutorify-be-feedback:dev
    restart: no
    build:
      context: ./feedback
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./feedback:/usr/src/app
      - ./shared:/usr/src/shared


  files:
    image: tutorify-be-files:dev
    restart: no
    build:
      context: ./files
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./files:/usr/src/app


  class-and-category:
    image: tutorify-be-class-and-category:dev
    restart: no
    build:
      context: ./class-and-category
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./class-and-category:/usr/src/app
      - ./shared:/usr/src/shared


  tutor-apply-for-class:
    image: tutorify-be-tutor-apply-for-class:dev
    restart: no
    build:
      context: ./tutor-apply-for-class
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./tutor-apply-for-class:/usr/src/app
      - ./shared:/usr/src/shared


  student-favorite-tutor:
    image: tutorify-be-student-favorite-tutor:dev
    restart: no
    build:
      context: ./student-favorite-tutor
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./student-favorite-tutor:/usr/src/app
      - ./shared:/usr/src/shared


  tutor-query:
    image: tutorify-be-tutor-query:dev
    restart: no
    build:
      context: ./tutor-query
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./tutor-query:/usr/src/app
      - ./shared:/usr/src/shared


  address:
    image: tutorify-be-address:dev
    restart: no
    build:
      context: ./address
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./address:/usr/src/app
      - ./shared:/usr/src/shared


  class-session:
    image: tutorify-be-class-session:dev
    restart: no
    build:
      context: ./class-session
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./class-session:/usr/src/app
      - ./shared:/usr/src/shared


  report:
    image: tutorify-be-report:dev
    restart: no
    build:
      context: ./report
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./report:/usr/src/app
      - ./shared:/usr/src/shared


  user-preferences:
    image: tutorify-be-user-preferences:dev
    restart: no
    build:
      context: ./user-preferences
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./user-preferences:/usr/src/app
      - ./shared:/usr/src/shared


  rabbitmq:
    restart: no
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
