version: '3'

services:
  api-gateway:
    restart: on-failure
    ports:
      - "3000:3000"
    build:
      context: ./api-gateway
      target: production
    environment:
      NODE_ENV: production
    env_file: ./api-gateway/.env.example
    volumes:
       - ./api-gateway:/usr/src/app
       - /usr/src/app/node_modules


  auth:
    restart: on-failure
    build:
      context: ./auth
      target: production
    environment:
      NODE_ENV: production
    env_file: ./auth/.env.example
    volumes:
       - ./auth:/usr/src/app
       - /usr/src/app/node_modules


  mailer:
    restart: on-failure
    build:
      context: ./mailer
      target: production
    environment:
      NODE_ENV: production
    env_file: ./mailer/.env.example
    volumes:
       - ./mailer:/usr/src/app
       - /usr/src/app/node_modules


  verification-token:
    restart: on-failure
    build:
      context: ./verification-token
      target: production
    environment:
      NODE_ENV: production
    env_file: ./verification-token/.env.example
    volumes:
       - ./verification-token:/usr/src/app
       - /usr/src/app/node_modules


  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
