services:
  api-gateway:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-api-gateway:prod
    restart: on-failure
    ports:
      - "3000:3000"
    build:
      context: ./api-gateway
      target: production
    environment:
      NODE_ENV: production
    env_file: ./api-gateway/.env
    depends_on:
      - rabbitmq


  auth:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-auth:prod
    restart: on-failure
    build:
      context: ./auth
      target: production
    environment:
      NODE_ENV: production
    env_file: ./auth/.env


  mailer:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-mailer:prod
    restart: on-failure
    build:
      context: ./mailer
      target: production
    environment:
      NODE_ENV: production
    env_file: ./mailer/.env


  verification-token:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-verification-token:prod
    restart: on-failure
    build:
      context: ./verification-token
      target: production
    environment:
      NODE_ENV: production
    env_file: ./verification-token/.env


  feedback:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-feedback:prod
    restart: on-failure
    build:
      context: ./feedback
      target: production
    environment:
      NODE_ENV: production
    env_file: ./feedback/.env


  files:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-files:prod
    restart: on-failure
    build:
      context: ./files
      target: production
    environment:
      NODE_ENV: production
    env_file: ./files/.env


  class-and-category:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-class-and-category:prod
    restart: on-failure
    build:
      context: ./class-and-category
      target: production
    environment:
      NODE_ENV: production
    env_file: ./class-and-category/.env


  tutor-apply-for-class:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-tutor-apply-for-class:prod
    restart: on-failure
    build:
      context: ./tutor-apply-for-class
      target: production
    environment:
      NODE_ENV: production
    env_file: ./tutor-apply-for-class/.env


  student-favorite-tutor:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-student-favorite-tutor:prod
    restart: on-failure
    build:
      context: ./student-favorite-tutor
      target: production
    environment:
      NODE_ENV: production
    env_file: ./student-favorite-tutor/.env


  tutor-query:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-tutor-query:prod
    restart: on-failure
    build:
      context: ./tutor-query
      target: production
    environment:
      NODE_ENV: production
    env_file: ./tutor-query/.env

  address:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-address:prod
    restart: on-failure
    build:
      context: ./address
      target: production
    environment:
      NODE_ENV: production
    env_file: ./address/.env

  class-session:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-class-session:prod
    restart: on-failure
    build:
      context: ./class-session
      target: production
    environment:
      NODE_ENV: production
    env_file: ./class-session/.env

  report:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-report:prod
    restart: on-failure
    build:
      context: ./report
      target: production
    environment:
      NODE_ENV: production
    env_file: ./report/.env

  user-preferences:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-user-preferences:prod
    restart: on-failure
    build:
      context: ./user-preferences
      target: production
    environment:
      NODE_ENV: production
    env_file: ./user-preferences/.env

  notification:
    image: asia-southeast1-docker.pkg.dev/ace-computer-422002-u9/tutorify-docker-repo/tutorify-be-notification:prod
    restart: on-failure
    build:
      context: ./notification
      target: production
    environment:
      NODE_ENV: production
    env_file: ./notification/.env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
