version: '3'

services:
  api-gateway:
    image: tutorify-be-api-gateway:dev
    restart: on-failure
    build:
      context: ./api-gateway
      target: development
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules

  auth:
    image: tutorify-be-auth:dev
    restart: on-failure
    build:
      context: ./auth
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules

  mailer:
    image: tutorify-be-mailer:dev
    restart: on-failure
    build:
      context: ./mailer
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./mailer:/usr/src/app
      - /usr/src/app/node_modules

  verification-token:
    image: tutorify-be-api-gateway:dev
    restart: on-failure
    build:
      context: ./verification-token
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./verification-token:/usr/src/app
      - /usr/src/app/node_modules

  feedback:
    image: tutorify-be-feedback:dev
    restart: on-failure
    build:
      context: ./feedback
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./feedback:/usr/src/app
      - /usr/src/app/node_modules

  files:
    image: tutorify-be-files:dev
    restart: on-failure
    build:
      context: ./files
      target: development
    environment:
      NODE_ENV: development
    volumes:
      - ./files:/usr/src/app
      - /usr/src/app/node_modules


  rabbitmq:
    restart: on-failure
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
