version: '3'

services:
  api-gateway:
    build:
      context: ./api-gateway
      target: production
    command: npm run start:prod
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    volumes:
       - ./api-gateway:/usr/src/app

  auth:
    build:
      context: ./auth
      target: production
    command: npm run start:prod
    environment:
      NODE_ENV: production
    volumes:
       - ./auth:/usr/src/app

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
