version: '3'

services:
  api-gateway:
    image: tutorify.azurecr.io/tutorify-be-api-gateway:prod
    restart: on-failure
    ports:
      - "3000:3000"
    build:
      context: ./api-gateway
      target: production
    environment:
      NODE_ENV: production
    env_file: ./api-gateway/.env.example
    volumes:
       - ./api-gateway:/usr/src/app
       - /usr/src/app/node_modules


  auth:
    image: tutorify.azurecr.io/tutorify-be-auth:prod
    restart: on-failure
    build:
      context: ./auth
      target: production
    environment:
      NODE_ENV: production
    env_file: ./auth/.env.example
    volumes:
       - ./auth:/usr/src/app
       - /usr/src/app/node_modules


  mailer:
    image: tutorify.azurecr.io/tutorify-be-mailer:prod
    restart: on-failure
    build:
      context: ./mailer
      target: production
    environment:
      NODE_ENV: production
    env_file: ./mailer/.env.example
    volumes:
       - ./mailer:/usr/src/app
       - /usr/src/app/node_modules


  verification-token:
    image: tutorify.azurecr.io/tutorify-be-verification-token:prod
    restart: on-failure
    build:
      context: ./verification-token
      target: production
    environment:
      NODE_ENV: production
    env_file: ./verification-token/.env.example
    volumes:
       - ./verification-token:/usr/src/app
       - /usr/src/app/node_modules


  feedback:
    image: tutorify.azurecr.io/tutorify-be-feedback:prod
    restart: on-failure
    build:
      context: ./feedback
      target: production
    environment:
      NODE_ENV: production
    env_file: ./feedback/.env.example
    volumes:
       - ./feedback:/usr/src/app
       - /usr/src/app/node_modules

  files:
    image: tutorify.azurecr.io/tutorify-be-files:prod
    restart: on-failure
    build:
      context: ./files
      target: production
    environment:
      NODE_ENV: production
    env_files: ./files/.env
    volumes:
       - ./files:/usr/src/app
       - /usr/src/app/node_modules

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
