version: '3'

services:
  nest-cli:
    image: node:18-alpine
    command: npm install -g @nestjs/cli
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    deploy:
      replicas: 0

  api-gateway:
    build:
      context: ./api-gateway
      target: development
    ports:
      - "3000:3000"
    command: npm run start:dev
    environment:
      NODE_ENV: development
    volumes:
      - ./api-gateway:/usr/src/app
    depends_on:
      - nest-cli

  auth:
    build:
      context: ./auth
      target: development
    command: npm run start:dev
    environment:
      NODE_ENV: development
    volumes:
      - ./auth:/usr/src/app
    depends_on:
      - nest-cli

  mailer:
    build:
      context: ./mailer
      target: development
    command: npm run start:dev
    environment:
      NODE_ENV: development
    volumes:
      - ./mailer:/usr/src/app
    depends_on:
      - nest-cli

  verification-token:
    build:
      context: ./verification-token
      target: development
    command: npm run start:dev
    environment:
      NODE_ENV: development
    volumes:
      - ./verification-token:/usr/src/app
    depends_on:
      - nest-cli

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  nginx:
    build:
      dockerfile: ./nginx/build/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - .:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - api-gateway
