export enum ApplicationStatus {
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    CANCELLED = 'CANCELLED',
    FILLED = 'FILLED',
    CLASS_DELETED = 'CLASS_DELETED',
    PENDING = 'PENDING',
}
